/**
 * AUTO-GENERATED by scripts/register-plugins.mjs — do not edit manually.
 * Rebuilt from workspace plugins in /plugins.
 */

import type { PluginHookContribution } from '@/types/plugin';

// (no workspace plugins found)

const registeredHooks: PluginHookContribution[] = [
  // (no plugin hooks found)
];

export default registeredHooks;
