/**
 * AUTO-GENERATED by scripts/register-plugins.mjs — do not edit manually.
 * Rebuilt from workspace plugins in /plugins.
 */

import type { PluginHookContribution } from '@/types/plugin';

import plugin0 from '../../plugins/pluradash/src/index';

const registeredHooks: PluginHookContribution[] = [
  ...(plugin0.hooks ?? []),
];

export default registeredHooks;
