/**
 * AUTO-GENERATED by scripts/install-plugins.mjs — do not edit manually.
 *
 * This file is regenerated every time install-plugins.mjs runs.
 * It flattens build-time hook contributions from installed plugins.
 */

import type { PluginHookContribution } from '@/types/plugin';

const registeredHooks: PluginHookContribution[] = [];

export default registeredHooks;
