// AUTO-GENERATED by scripts/register-plugins.mjs — do not edit manually.
import type { PluginApiMetadata, PluginCapabilityDescriptor, PluginHookDescriptor } from '@/types/plugin';

export interface RegisteredPluginMetadata {
  pluginId: string;
  hookMetadata: PluginHookDescriptor[];
  apiMetadata: PluginApiMetadata | null;
  capabilities: PluginCapabilityDescriptor[];
}

const registeredPluginMetadata: RegisteredPluginMetadata[] = [
  {
    "pluginId": "pluradash",
    "hookMetadata": [
      {
        "key": "pluradash-default-landing-option",
        "target": "settings.defaultLanding.options",
        "scope": "ui",
        "kind": "transform",
        "order": 100,
        "description": "Adds PluraDash to the core default landing page selector when the plugin is available to the current user."
      },
      {
        "key": "pluradash-default-landing-resolver",
        "target": "settings.defaultLanding.resolve",
        "scope": "ui",
        "kind": "transform",
        "order": 100,
        "description": "Resolves PluraDash as the preferred landing page for authenticated support users when no other valid preference exists."
      },
      {
        "key": "pluradash-tenant-storage-policy",
        "target": "storage.tenant.policy",
        "scope": "api",
        "kind": "transform",
        "order": 100,
        "description": "Enables tenant-scoped managed storage for PluraDash support users and grants unlimited access to super-admins."
      },
      {
        "key": "pluradash-tenant-storage-sources",
        "target": "storage.tenant.sources",
        "scope": "api",
        "kind": "transform",
        "order": 100,
        "description": "Restricts support users to the managed R2 media source while leaving super-admin source access unchanged."
      }
    ],
    "apiMetadata": null,
    "capabilities": [
      {
        "key": "pluradash-dashboard",
        "kind": "interface",
        "targets": [
          "/plugins/pluradash"
        ],
        "description": "Adds the PluraDash tenant dashboard entrypoint for support users."
      },
      {
        "key": "pluradash-default-landing",
        "kind": "hook",
        "targets": [
          "settings.defaultLanding.options",
          "settings.defaultLanding.resolve"
        ],
        "description": "Extends the core landing page preference with a PluraDash destination."
      }
    ]
  }
];

export function getRegisteredPluginMetadata(): RegisteredPluginMetadata[] {
  return registeredPluginMetadata;
}
