// AUTO-GENERATED by scripts/register-plugins.mjs — do not edit manually.
import type { PluginApiMetadata, PluginCapabilityDescriptor, PluginHookDescriptor } from '@/types/plugin';

export interface RegisteredPluginMetadata {
  pluginId: string;
  hookMetadata: PluginHookDescriptor[];
  apiMetadata: PluginApiMetadata | null;
  capabilities: PluginCapabilityDescriptor[];
}

const registeredPluginMetadata: RegisteredPluginMetadata[] = [
  {
    "pluginId": "pluradash",
    "hookMetadata": [
      {
        "key": "pluradash-default-landing-option",
        "target": "settings.defaultLanding.options",
        "scope": "ui",
        "kind": "transform",
        "order": 100,
        "description": "Adds PluraDash to the core default landing page selector when the plugin is available to the current user."
      },
      {
        "key": "pluradash-default-landing-resolver",
        "target": "settings.defaultLanding.resolve",
        "scope": "ui",
        "kind": "transform",
        "order": 100,
        "description": "Resolves PluraDash as the preferred landing page for authenticated support users when no other valid preference exists."
      },
      {
        "key": "pluradash-default-landing-path",
        "target": "settings.defaultLanding.path",
        "scope": "ui",
        "kind": "transform",
        "order": 100,
        "description": "Maps the PluraDash landing-view key to the plugin route."
      },
      {
        "key": "pluradash-tenant-storage-policy",
        "target": "storage.tenant.policy",
        "scope": "api",
        "kind": "transform",
        "order": 100,
        "description": "Enables tenant-scoped managed storage for PluraDash support users."
      },
      {
        "key": "pluradash-tenant-storage-sources",
        "target": "storage.tenant.sources",
        "scope": "api",
        "kind": "transform",
        "order": 100,
        "description": "Restricts support users to the managed R2 media source for PluraDash-managed storage."
      },
      {
        "key": "pluradash-media-url-resolver",
        "target": "media.url.resolve",
        "scope": "ui",
        "kind": "transform",
        "order": 100,
        "description": "Rewrites plugin-owned tenant media URLs onto the core worker delivery route."
      },
      {
        "key": "pluradash-form-file-builder",
        "target": "forms.fileUpload.builder",
        "scope": "ui",
        "kind": "transform",
        "order": 100,
        "description": "Marks PluraDash as the file-upload provider inside the forms builder when the plugin is enabled for the selected workspace."
      },
      {
        "key": "pluradash-form-upload-provider",
        "target": "forms.fileUpload.upload",
        "scope": "api",
        "kind": "transform",
        "order": 100,
        "description": "Stores uploaded form files inside the tenant-scoped PluraDash archive structure."
      },
      {
        "key": "pluradash-form-notification-links",
        "target": "forms.fileUpload.notification",
        "scope": "api",
        "kind": "transform",
        "order": 100,
        "description": "Adds PluraDash download links for uploaded form files to notification e-mails."
      }
    ],
    "apiMetadata": null,
    "capabilities": [
      {
        "key": "pluradash-dashboard",
        "kind": "interface",
        "targets": [
          "/plugins/pluradash"
        ],
        "description": "Adds the PluraDash tenant dashboard entrypoint for support users."
      },
      {
        "key": "pluradash-default-landing",
        "kind": "hook",
        "targets": [
          "settings.defaultLanding.options",
          "settings.defaultLanding.resolve",
          "settings.defaultLanding.path"
        ],
        "description": "Extends the core landing page preference with a PluraDash destination."
      },
      {
        "key": "pluradash-tenant-media-routing",
        "kind": "hook",
        "targets": [
          "storage.tenant.policy",
          "storage.tenant.sources",
          "media.url.resolve",
          "forms.fileUpload.builder",
          "forms.fileUpload.upload",
          "forms.fileUpload.notification"
        ],
        "description": "Owns the PluraDash-specific tenant media and form-file routing rules without hardcoding bucket names into core."
      }
    ]
  }
];

export function getRegisteredPluginMetadata(): RegisteredPluginMetadata[] {
  return registeredPluginMetadata;
}
