// AUTO-GENERATED by scripts/install-plugins.mjs — do not edit manually.
// Re-run `npm run plugin:install` to regenerate.
import type { PluginApiMetadata, PluginCapabilityDescriptor, PluginHookDescriptor } from '@/types/plugin';

export interface RegisteredPluginMetadata {
  pluginId: string;
  hookMetadata: PluginHookDescriptor[];
  apiMetadata: PluginApiMetadata | null;
  capabilities: PluginCapabilityDescriptor[];
}

const registeredPluginMetadata: RegisteredPluginMetadata[] = [];

export function getRegisteredPluginMetadata(): RegisteredPluginMetadata[] {
  return registeredPluginMetadata;
}
